spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CommonData
    username: dev_user
    password: dev_pass
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        maximum-pool-size: 10
        minimum-idle: 3
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000
        auto-commit: true
        transaction-isolation: TRANSACTION_READ_COMMITTED
        connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: vz53iy67d9aib705edaxi2cgy3o839y3kostapo
  access-token-ttl: 10m
  refresh-token-ttl: 1d
  remember-me-ttl: 30d


logging:
  level:
    root: INFO
    #org.springframework.security: DEBUG