server:
  port: ${PORT:8080}
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_SERVICE_HOST:localhost}
      port: ${REDIS_SERVICE_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      connect-timeout: 500ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/CommonData}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        maximum-pool-size: 10
        minimum-idle: 3
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000
        auto-commit: true
        transaction-isolation: TRANSACTION_READ_COMMITTED
        connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: vz53iy67d9aib705edaxi2cgy3o839y3kostapo
  access-token-ttl: 1m
  refresh-token-ttl: 3m
  remember-me-ttl: 1d

rate-limit:
  duration: 1
  capacity:
    main: 10
    options: 50

logging:
  level:
    root: INFO
    #org.springframework.security: DEBUG
    #com.zaxxer.hikari: DEBUG
    #org.hibernate: DEBUG